### ISSUE TITLE
Fail to create the PRs

### ISSUE THREAD

**Issue by otavio** [zeebe-io/backport-action#76] opened 2021-06-26 13:14 UTC
It seems there is a missing step on the README.

It fails as:

https://github.com/OSSystemsEmbeddedLinux/meta-ossystems-base/runs/2921092978?check_suite_focus=true#step:3:93

**Comment by korthout** [comment] 2021-06-27 11:49
@otavio Looks like you're trying to run the action against pull requests from a forked repo. To enable that, please use `pull_request_target` as the event type instead of `pull_request`. Please also be aware of the security notes GitHub describes about using this: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target

Closing as duplicate of #41.

**Closed by korthout** 2021-06-27 11:49 UTC
